window.searchable.push("Nucleus Accumbens (ACB)");
window.searchable.push("Abducens nucleus (VI)");
window.searchable.push("Accessory olfactory bulb (AOB)");
window.searchable.push("Agranular insular area dorsal part (AId)");
window.searchable.push("Agranular insular area posterior part (AIp)");
window.searchable.push("Agranular insular area ventral part (AIv)");
window.searchable.push("Ammon Horn (CA)");
window.searchable.push("Ansiform lobule (AN)");
window.searchable.push("Anterior amygdaloid area (AAA)");
window.searchable.push("Anterior cingulate area (ACA)");
window.searchable.push("Anterior cingulate area dorsal part (ACAd)");
window.searchable.push("Anterior cingulate area ventral part (ACAv)");
window.searchable.push("Anterior hypothalamic central part (AHNc)");
window.searchable.push("Anterior hypothalamic dorsal part (AHNd)");
window.searchable.push("Anterior hypothalamic nucleus anterior part (AHNa)");
window.searchable.push("Anterior hypothalamic posterior part (AHNp)");
window.searchable.push("Anterior laterolateral visual area (VISlla)");
window.searchable.push("Anterior olfactory nucleus (AON)");
window.searchable.push("Anterior periventricular nucleus of the hypothalamus (PVa)");
window.searchable.push("Anterior pretectal nucleus (APN)");
window.searchable.push("Anterior tegmental nucleus (AT)");
window.searchable.push("Anterodorsal nucleus of the thalamus (AD)");
window.searchable.push("Anterodorsal preoptic nucleus (ADP)");
window.searchable.push("Anterolateral visual area (VISal)");
window.searchable.push("Anteromedial nucleus of thalamus dorsal part (AMd)");
window.searchable.push("Anteromedial nucleus of thalamus ventral part (AMv)");
window.searchable.push("Anteromedial visual area (VISam)");
window.searchable.push("Anteroventral nucleus of thalamus (AV)");
window.searchable.push("Anteroventral periventricular nucleus (AVPV)");
window.searchable.push("Anteroventral preoptic nucleus (AVP)");
window.searchable.push("Area postrema (AP)");
window.searchable.push("Barrington nucleus (B)");
window.searchable.push("Basal nucleus of the dorsal horn (BN)");
window.searchable.push("Basolateral nucleus of the amygdala anterior part (BLAa)");
window.searchable.push("Basolateral nucleus of the amygdala posterior part (BLAp)");
window.searchable.push("Basomedial nucleus of the amygdala anterior part (BMAa)");
window.searchable.push("Basomedial nucleus of the amygdala posterior part (BMAp)");
window.searchable.push("Bed nuclei of the stria terminalis anterior division dorsomedial nucleus (BSTdm)");
window.searchable.push("Bed nuclei of the stria terminalis anterior division fusiform nucleus (BSTfu)");
window.searchable.push("Bed nuclei of the stria terminalis anterior division magnocellular nucleus (BSTmg)");
window.searchable.push("Bed nuclei of the stria terminalis anterior division ventral nucleus (BSTv)");
window.searchable.push("Bed nuclei of the stria terminalis anterolateral area (BSTal)");
window.searchable.push("Bed nuclei of the stria terminalis oval nucleus (BSTov)");
window.searchable.push("Bed nuclei of the stria terminalis posterior division interfascicular nucleus (BSTif)");
window.searchable.push("Bed nuclei of the stria terminalis posterior division principal nucleus (BSTpr)");
window.searchable.push("Bed nuclei of the stria terminalis rhomboid nucleus (BSTrh)");
window.searchable.push("Bed nucleus of the accessory olfactory part (BA)");
window.searchable.push("Caudoputamen (CP)");
window.searchable.push("Central cervical nucleus (CEC)");
window.searchable.push("Central gray of the spinal cord (CGS)");
window.searchable.push("Central lateral nucleus of the thalamus (CL)");
window.searchable.push("Central linear nucleus raphe (CLI)");
window.searchable.push("Central medial nucleus of the thalamus (CM)");
window.searchable.push("Central nucleus of amygdala capsular part (CEAc)");
window.searchable.push("Claustrum (CLA)");
window.searchable.push("Copula pyramidis (COPY)");
window.searchable.push("Cortical nucleus of the amygdala anterior part (COAa)");
window.searchable.push("Cortical nucleus of the amygdala posterior part lateral zone (COApl)");
window.searchable.push("Cortical nucleus of the amygdala posterior part medial zone (COApm)");
window.searchable.push("Culmen (CUL)");
window.searchable.push("Cuneate nucleus (CU)");
window.searchable.push("Cuneiform nucleus (CUN)");
window.searchable.push("Declive (VI) (DEC)");
window.searchable.push("Dentate gyrus (DG)");
window.searchable.push("Dentate nucleus (DN)");
window.searchable.push("Dorsal auditory areas (AUDd)");
window.searchable.push("Dorsal coclear nucleus (DCO)");
window.searchable.push("Dorsal motor nucleus of the vagus nerve (DMX)");
window.searchable.push("Dorsal nucleus of the spinal cord (DSN)");
window.searchable.push("Dorsal nucleus of the spinal cord caudal part (DSNc)");
window.searchable.push("Dorsal nucleus raphe (DR)");
window.searchable.push("Dorsal part of the lateral geniculate complex (LGd)");
window.searchable.push("Dorsal premammillary nucleus (PMd)");
window.searchable.push("Dorsal tegmental nucleus (DTN)");
window.searchable.push("Dorsomedial nucleus of the hypothalamus anterior part (DMHa)");
window.searchable.push("Dorsomedial nucleus of the hypothalamus posterior part (DMHp)");
window.searchable.push("Dorsomedial nucleus of the hypothalamus ventral part (DMHv)");
window.searchable.push("Ectorhinal area (ECT)");
window.searchable.push("Edinger-Westphal nucleus (EW)");
window.searchable.push("Efferent cochlear group (ECO)");
window.searchable.push("Efferent vestibular nucleus (EV)");
window.searchable.push("Endopiriform nucleus (EP)");
window.searchable.push("Entorhinal area medial part, dorsal zone (ENTm)");
window.searchable.push("Entorhinal area, lateral part (ENTl)");
window.searchable.push("External cuneate nucleus (ECU)");
window.searchable.push("Facial nucleus (VII)");
window.searchable.push("Fasciola cinerea (FC)");
window.searchable.push("Fastigial nucleus (FN)");
window.searchable.push("Field CA1 (CA1)");
window.searchable.push("Field CA2 (CA2)");
window.searchable.push("Field CA3 (CA3)");
window.searchable.push("Fields of Forel (FF)");
window.searchable.push("Flocculus (FL)");
window.searchable.push("Folium-tuber vermis (VII) (FOTU)");
window.searchable.push("Fundus of the striatum (FS)");
window.searchable.push("Geniculate group of the dorsal thalamus (GENd)");
window.searchable.push("Geniculate group of the ventral thalamus (GENv)");
window.searchable.push("Globus Pallidus (GP)");
window.searchable.push("Gracile nucleus (GR)");
window.searchable.push("Gustatory areas (GU)");
window.searchable.push("Hypoglossal nucleus (XII)");
window.searchable.push("Induseum griseum (IG)");
window.searchable.push("Inferior colliculus central nucleus (ICc)");
window.searchable.push("Inferior colliculus dorsal nucleus (ICd)");
window.searchable.push("Inferior colliculus external nucleus (ICe)");
window.searchable.push("Inferior olivary complex (IO)");
window.searchable.push("Inferior salivatory nucleus (ISN)");
window.searchable.push("Infracerebellar nucleus (ICB)");
window.searchable.push("Infralimbic area (ILA)");
window.searchable.push("Interanterodorsal nucleus of the thalamus (IAD)");
window.searchable.push("Interanteromedial nucleus of the thalamus (IAM)");
window.searchable.push("Interfascicular nucleus raphe (IF)");
window.searchable.push("Intergeniculate leaflet of the lateral geniculate complex (IGL)");
window.searchable.push("Intermediate Gray of the Spinal Cord (IH)");
window.searchable.push("Intermediate periventricular nucleus of the hypothalamus (PVI)");
window.searchable.push("Intermediodorsal nucleus of the thalamus (IMD)");
window.searchable.push("Intermediolateral column of the spinal cord parasympathetic column (IMLp)");
window.searchable.push("Intermediolateral column of the spinal cord sympathetic column (IMLs)");
window.searchable.push("Intermediomedial column of the spinal cord (IMM)");
window.searchable.push("Interpeduncular nucleus (IPN)");
window.searchable.push("Interposed nucleus (IP)");
window.searchable.push("Interstitial nucleus of Cajal (INC)");
window.searchable.push("Lateral cervical nucleus (LCN)");
window.searchable.push("Lateral dorsal nucleus of thalamus (LD)");
window.searchable.push("Lateral habenula (LH)");
window.searchable.push("Lateral Hypothalamic Area, anterior division (LHAa)");
window.searchable.push("Lateral mammillary nucleus (LM)");
window.searchable.push("Lateral posterior nucleus of the thalamus (LP)");
window.searchable.push("Lateral preoptic area (LPO)");
window.searchable.push("Lateral septal nucleus (LS)");
window.searchable.push("Lateral septal nucleus caudal [caudodorsal] part (LSc)");
window.searchable.push("Lateral septal nucleus rostral [rostroventral] part (LSr)");
window.searchable.push("Lateral septal nucleus ventral part (LSv)");
window.searchable.push("Lateral terminal nucleus of the accessory optic tract (LT)");
window.searchable.push("Lateral vestibular nucleus (LAV)");
window.searchable.push("Layer 6b [layer 7, subplate, deep cortex, claustral complex] (CTXsp)");
window.searchable.push("Magnocellular preoptic nucleus (MA)");
window.searchable.push("Magnocellular reticular nucleus (MARN)");
window.searchable.push("Main olfactory bulb (MOB)");
window.searchable.push("Medial accessory nucleus (MAN)");
window.searchable.push("Medial geniculate complex dorsal part (MGd)");
window.searchable.push("Medial geniculate complex medial part (MGm)");
window.searchable.push("Medial geniculate complex ventral part (MGv)");
window.searchable.push("Medial habenula (MH)");
window.searchable.push("Medial mammillary nucleus (MM)");
window.searchable.push("Medial nucleus of the amygdala anterodorsal part (MEAad)");
window.searchable.push("Medial nucleus of the amygdala anteroventral part (MEAav)");
window.searchable.push("Medial nucleus of the amygdala posterodorsal part (MEApd)");
window.searchable.push("Medial nucleus of the amygdala posteroventral part (MEApv)");
window.searchable.push("Medial preoptic nucleus central part (MPNc)");
window.searchable.push("Medial preoptic nucleus lateral part (MPNl)");
window.searchable.push("Medial preoptic nucleus medial part (MPNm)");
window.searchable.push("Medial pretectal area (MPT)");
window.searchable.push("Medial septal nucleus (MS)");
window.searchable.push("Medial terminal nucleus of the accessory optic tract (MT)");
window.searchable.push("Medial vestibular nucleus (MV)");
window.searchable.push("Median eminence (ME)");
window.searchable.push("Median preoptic nucleus (MEPO)");
window.searchable.push("Mediodorsal nucleus of the thalamus central part (MDc)");
window.searchable.push("Mediodorsal nucleus of the thalamus lateral part (MDl)");
window.searchable.push("Mediodorsal nucleus of the thalamus medial part (MDm)");
window.searchable.push("Medullary reticular nucleus dorsal part (MDRNd)");
window.searchable.push("Medullary reticular nucleus ventral part (MDRNv)");
window.searchable.push("Mesencephalic nucleus of the trigeminal (MEV)");
window.searchable.push("Mesencephalic reticular nucleus proper (MRN_p)");
window.searchable.push("Motor nucleus of the trigeminal (V)");
window.searchable.push("Nucleus ambiguus dorsal division (AMBd)");
window.searchable.push("Nucleus ambiguus, ventral division (AMBv)");
window.searchable.push("Nucleus incertus (NI)");
window.searchable.push("Nucleus intercalatus (NIS)");
window.searchable.push("Nucleus of Darkschewitsch (ND)");
window.searchable.push("Nucleus of Roller (NR)");
window.searchable.push("Nucleus of the brachium of the inferior colliculus (NB)");
window.searchable.push("Nucleus of the diagonal band (NDB)");
window.searchable.push("Nucleus of the lateral lemniscus (NLL)");
window.searchable.push("Nucleus of the optic tract (NOT)");
window.searchable.push("Nucleus of the posterior commissure (NPC)");
window.searchable.push("Nucleus of the solitary tract (NTS)");
window.searchable.push("Nucleus of the trapezoid body (NTB)");
window.searchable.push("Nucleus prepositus (PRP)");
window.searchable.push("Nucleus proprius of the spinal cord (NP)");
window.searchable.push("Nucleus raphe magnus (RM)");
window.searchable.push("Nucleus raphe obscurus (RO)");
window.searchable.push("Nucleus raphe pallidus (RPA)");
window.searchable.push("Nucleus raphe pontis (RPO)");
window.searchable.push("Nucleus sagulum (SAG)");
window.searchable.push("Nucleus x (x)");
window.searchable.push("Nucleus y (y)");
window.searchable.push("Nucleus z (z)");
window.searchable.push("Olfactory tubercle (OT)");
window.searchable.push("Olivary pretectal nucleus (OP)");
window.searchable.push("Orbital area lateral part (ORBl)");
window.searchable.push("Orbital area medial part (ORBm)");
window.searchable.push("Orbital area ventral part (ORBv)");
window.searchable.push("Orbital area ventrolateral part (ORBvl)");
window.searchable.push("Parabrachial nucleus (PB)");
window.searchable.push("Parafascicular nucleus (PF)");
window.searchable.push("Paraflocculus (PFL)");
window.searchable.push("Parageminal nucleus (PBG)");
window.searchable.push("Paragigantocellular reticular nucleus (PGRN)");
window.searchable.push("Paramedian lobule (PRM)");
window.searchable.push("Paramedian reticular nucleus (PMR)");
window.searchable.push("Parasolitary nucleus (PAS)");
window.searchable.push("Parastrial nucleus (PS)");
window.searchable.push("Parasubiculum (PAR)");
window.searchable.push("Paratrigeminal nucleus (PAT)");
window.searchable.push("Paraventricular nucleus of the hypothalamus, descending division (PVHd)");
window.searchable.push("Paraventricular nucleus of the hypothalamus, magnocellular division (PVHm)");
window.searchable.push("Paraventricular nucleus of the hypothalamus, parvicellular division (PVHp)");
window.searchable.push("Parvicellular reticular nucleus (PARN)");
window.searchable.push("Pedunculopontine nucleus (PPN)");
window.searchable.push("Periaqueductal gray (PAG)");
window.searchable.push("Peripeduncular nucleus (PP)");
window.searchable.push("Perireunensis nucleus (PR)");
window.searchable.push("Perirhinal area (PERI)");
window.searchable.push("Phrenic nucleus (PN)");
window.searchable.push("Piriform area (PIR)");
window.searchable.push("Piriform-amygdaloid area (PAA)");
window.searchable.push("Pontine central gray (PCG)");
window.searchable.push("Pontine gray (PG)");
window.searchable.push("Pontine reticular nucleus caudal part (PRNc)");
window.searchable.push("Pontine reticular nucleus rostral part (PRNr)");
window.searchable.push("Posterior complex of the thalamus (PO)");
window.searchable.push("Posterior hypothalamic nucleus (PH)");
window.searchable.push("Posterior limiting nucleus of the thalamus (POL)");
window.searchable.push("Posterior nucleus of the amygdala (PA)");
window.searchable.push("Posterior periventricular nucleus of the hypothalamus (PVp)");
window.searchable.push("Posterodorsal preoptic nucleus (PD)");
window.searchable.push("Primary visual area (VISp)");
window.searchable.push("Posterolateral visual area (VISpl)");
window.searchable.push("Postpiriform transition area (TR)");
window.searchable.push("Postsubiculum (POST)");
window.searchable.push("Prelimbic area (PL)");
window.searchable.push("Preoptic periventricular nucleus (PVpo)");
window.searchable.push("Presubiculum (PRE)");
window.searchable.push("Primary auditory area (AUDp)");
window.searchable.push("Primary motor area (MOp)");
window.searchable.push("Primary somatosensory area (SSp)");
window.searchable.push("Principal sensory nucleus of the trigeminal (PSV)");
window.searchable.push("Pyramus (PYR)");
window.searchable.push("Red nucleus (RN)");
window.searchable.push("Reticular nucleus of the thalamus (RT)");
window.searchable.push("Retrochiasmatic area (RCH)");
window.searchable.push("Retrorubral area (RR)");
window.searchable.push("Retrosplenial area dorsal part (RSPd)");
window.searchable.push("Retrosplenial area lateral agranular part (RSPagl)");
window.searchable.push("Retrosplenial area ventral part (RSPv)");
window.searchable.push("Retrosplenial area ventral part zone a (RSPv-a)");
window.searchable.push("Retrosplenial area ventral part zone b/c (RSPv-b-c)");
window.searchable.push("Rhomboid nucleus (RH)");
window.searchable.push("Rostral linear nucleus raphe (RL)");
window.searchable.push("Rostrolateral visual area (VISrl)");
window.searchable.push("Secondary motor area (MOs)");
window.searchable.push("Septofimbrial nucleus (SF)");
window.searchable.push("Septohippocampal nucleus (SH)");
window.searchable.push("Simple lobule (SIM)");
window.searchable.push("Spinal nucleus of the trigeminal caudal part (SPVC)");
window.searchable.push("Spinal nucleus of the trigeminal interpolar part (SPVI)");
window.searchable.push("Spinal nucleus of the trigeminal oral part (SPVO)");
window.searchable.push("Spinal vestibular nucleus (SPIV)");
window.searchable.push("Subcoeruleus nucleus (SLC)");
window.searchable.push("Subfornical organ (SFO)");
window.searchable.push("Subiculum (SUB)");
window.searchable.push("Subiculum dorsal part (SUBd)");
window.searchable.push("Subiculum ventral part (SUBv)");
window.searchable.push("Sublaterodorsal nucleus (SLD)");
window.searchable.push("Submedial nucleus of the thalamus (SMT)");
window.searchable.push("Subparafascicular nucleus magnocellular part (SPFm)");
window.searchable.push("Subparafascicular nucleus parvicellular part (SPFp)");
window.searchable.push("Subparaventricular zone (SBPV)");
window.searchable.push("Substantia gelatinosa of the spinal cord (SGE)");
window.searchable.push("Substantia innominata (SI)");
window.searchable.push("Substantia nigra (SN)");
window.searchable.push("Substantia nigra compact part (SNc)");
window.searchable.push("Substantia nigra reticular part (SNr)");
window.searchable.push("Subthalamic nucleus (STN)");
window.searchable.push("Supargenual nucleus (SG)");
window.searchable.push("Superior central nucleus raphe lateral part (CSl)");
window.searchable.push("Superior central nucleus raphe medial part (CSm)");
window.searchable.push("Superior colliculus (SC)");
window.searchable.push("Superior olivary complex lateral part (SOCl)");
window.searchable.push("Superior olivary complex medial part (SOCm)");
window.searchable.push("Superior olivary complex periolivary region (POR)");
window.searchable.push("Superior salivatory nucleus (SSN)");
window.searchable.push("Superior vestibular nucleus (SUV)");
window.searchable.push("Supplemental somatosensory area (SSs)");
window.searchable.push("Suprachiasmatic nucleus (SCH)");
window.searchable.push("Suprachiasmatic preoptic nucleus (PSCH)");
window.searchable.push("Suprageniculate nucleus (SGN)");
window.searchable.push("Supramammillary nucleus lateral part (SUMl)");
window.searchable.push("Supramammillary nucleus medial part (SUMm)");
window.searchable.push("Supraoptic nucleus (SO)");
window.searchable.push("Supraoptic nucleus, accessory supraoptic group (ASO)");
window.searchable.push("Supratrigeminal nucleus (SUT)");
window.searchable.push("Taenia tecta dorsal part (TTd)");
window.searchable.push("Taenia tecta ventral part (TTv)");
window.searchable.push("Tegmental reticular nucleus (TRN)");
window.searchable.push("Triangular nucleus of the septum (TRS)");
window.searchable.push("Tuberomammillary nucleus (TM)");
window.searchable.push("Vascular organ of the lamina terminalis (OV)");
window.searchable.push("Ventral anterior-lateral complex of the thalamus (VAL)");
window.searchable.push("Ventral auditory areas (AUDv)");
window.searchable.push("Ventral coclear nucleus anterior part (VCOa)");
window.searchable.push("Ventral coclear nucleus posterior part (VCOp)");
window.searchable.push("Ventral medial nucleus of the thalamus (VM)");
window.searchable.push("Ventral part of the lateral geniculate complex lateral zone (LGvl)");
window.searchable.push("Ventral part of the lateral geniculate complex medial zone (LGvm)");
window.searchable.push("Ventral posterolateral nucleus of the thalamus (VPL)");
window.searchable.push("Ventral posterolateral nucleus of the thalamus parvicellular part (VPLpc)");
window.searchable.push("Ventral posteromedial nucleus of the thalamus (VPM)");
window.searchable.push("Ventral posteromedial nucleus of the thalamus parvicellular part (VPMpc)");
window.searchable.push("Ventral premammillary nucleus (PMv)");
window.searchable.push("Ventral tegmental area (VTA)");
window.searchable.push("Ventral tegmental nucleus (VTN)");
window.searchable.push("Ventromedial nucleus of the hypothalamus anterior part (VMHa)");
window.searchable.push("Ventromedial nucleus of the hypothalamus central part (VMHc)");
window.searchable.push("Ventromedial nucleus of the hypothalamus dorsomedial part (VMHdm)");
window.searchable.push("Ventromedial nucleus of the hypothalamus ventrolateral part (VMHvl)");
window.searchable.push("Visceral area (VISC)");
window.searchable.push("Zona incerta (ZI)");
window.searchable.push("Zona incerta dopaminergic group (ZIda)");